Repository I2PC/scipion, pull requests merged in 2018-09, with the labels that each got.

#1727 Fix error when deleting a project in manager.py
  pyworkflow/manager.py
Labels: to-review

#1736 Do not divide by the gain in xmipp movie alignment protocols
  software/em/xmipp/applications/programs/movie_optical_alignment_cpu/movie_optical_alignment_cpu.cpp
  software/em/xmipp/libraries/reconstruction/movie_alignment_correlation.cpp
Labels: to-review

#1737 Convert gain
  pyworkflow/em/protocol/protocol_movies.py
  pyworkflow/gui/browser.py
  pyworkflow/tests/__init__.py
  pyworkflow/tests/em/protocols/test_protocols_motioncor2.py
Labels: to-review

#1747 Bug fixing in string concatenation
  install/script.py
Labels: to-review

#1750 fix tests after createproject not changing the working directory.
  pyworkflow/tests/tests.py
Labels: to-review

#1753 Fixed bug when gainImage is empty string
  pyworkflow/em/protocol/protocol_movies.py
Labels: to-review

#1749 Set png library as default=True
  install/script.py
Labels: bug, pluginization, to-review

#1762 Enabling CI
  .travis.yml
  sonar-project.properties
Labels: to-review

#1763 Bug fixing in xmipp's viewer.py: 'str' + 'int'
  pyworkflow/em/showj.py
Labels: betatesting, bug

#1761 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: to-review

#1769 Release 1.2.1 fixes
  pyworkflow/em/convert.py
  pyworkflow/em/packages/xmipp3/protocol_particle_pick_pairs.py
  pyworkflow/em/showj.py
  pyworkflow/gui/gui.py
  pyworkflow/project.py
  pyworkflow/protocol/protocol.py
Labels: to-review

#1775 close #1772
  pyworkflow/em/packages/relion/dataimport.py
Labels: to-review

#1755 Plugin installation as pip modules
  install/funcs.py
  install/install-plugin.py
  install/plugin_funcs.py
  install/script.py
  scipion
Labels: to-review

#1781 * Fix Bug/feature request for export workflow GUI window
  pyworkflow/gui/browser.py
  pyworkflow/gui/project/viewprotocols.py
Labels: to-review

#1782 Release 1.2.1 to devel
  pyworkflow/em/convert.py
  pyworkflow/em/packages/motioncorr/tests/test_protocols_motioncor2.py
  pyworkflow/em/packages/relion/dataimport.py
  pyworkflow/em/packages/xmipp3/protocol_particle_pick_pairs.py
  pyworkflow/em/protocol/protocol_movies.py
  pyworkflow/em/showj.py
  pyworkflow/gui/browser.py
  pyworkflow/gui/gui.py
  pyworkflow/manager.py
  pyworkflow/project.py
  pyworkflow/protocol/protocol.py
  pyworkflow/tests/__init__.py
  pyworkflow/tests/tests.py
  scipion
  software/em/xmipp/applications/programs/movie_optical_alignment_cpu/movie_optical_alignment_cpu.cpp
  software/em/xmipp/java/src/xmipp/viewer/particlepicker/training/AutopickRunnable.java
  software/em/xmipp/libraries/reconstruction/movie_alignment_correlation.cpp
Labels: to-review

#1784 Devel to pluginization
  .gitignore
  config/templates/protocols.template
  install/script.py
  pyworkflow/em/convert.py
  pyworkflow/em/metadata/constants.py
  pyworkflow/em/protocol/protocol_align_movies.py
  pyworkflow/em/protocol/protocol_movies.py
  pyworkflow/em/showj.py
  pyworkflow/em/viewer.py
  pyworkflow/gui/browser.py
  pyworkflow/gui/gui.py
  pyworkflow/gui/text.py
  pyworkflow/manager.py
  pyworkflow/project.py
  pyworkflow/protocol/protocol.py
  pyworkflow/tests/__init__.py
  pyworkflow/tests/em/workflows/test_workflow_modeling.py
  pyworkflow/tests/tests.py
  scipion
Labels: to-review

#1785 Fix protocols.template format
  config/templates/protocols.template
  pyworkflow/gui/project/viewprojects.py
Labels: to-review
